package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88-dev

import (
	"context"

	"github.com/magendooro/magento2-catalog-graphql-go/graph/model"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, search *string, filter *model.ProductAttributeFilterInput, pageSize *int, currentPage *int, sort *model.ProductAttributeSortInput) (*model.Products, error) {
	ps := 20
	if pageSize != nil {
		ps = *pageSize
	}
	cp := 1
	if currentPage != nil {
		cp = *currentPage
	}

	return r.ProductService.GetProducts(ctx, search, filter, sort, ps, cp)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, filters *model.CategoryFilterInput, pageSize *int, currentPage *int) (*model.CategoryResult, error) {
	ps := 20
	if pageSize != nil {
		ps = *pageSize
	}
	cp := 1
	if currentPage != nil {
		cp = *currentPage
	}
	return r.CategoryService.GetCategories(ctx, filters, ps, cp)
}

// CategoryList is the resolver for the categoryList field.
func (r *queryResolver) CategoryList(ctx context.Context, filters *model.CategoryFilterInput) ([]*model.CategoryTree, error) {
	return r.CategoryService.GetCategoryList(ctx, filters)
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id *int) (*model.CategoryTree, error) {
	if id == nil {
		return nil, nil
	}
	return r.CategoryService.GetCategoryByID(ctx, *id)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
