package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/magendooro/magento2-catalog-graphql-go/graph/model"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, search *string, filter *model.ProductAttributeFilterInput, pageSize *int, currentPage *int, sort *model.ProductAttributeSortInput) (*model.Products, error) {
	ps := 20
	if pageSize != nil {
		ps = *pageSize
	}
	cp := 1
	if currentPage != nil {
		cp = *currentPage
	}

	return r.ProductService.GetProducts(ctx, search, filter, sort, ps, cp)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
